server:
  port: 9999

jedis:
  host: 127.0.0.1
  port: 6379

user:
  user-name: tqx
  password: tqx
  dept-no: inspur

spring:
  application:
    name: rabbitmq-config
  rabbitmq:
    host: 139.129.14.25
    port: 5672
    username: guest
    password: guest
    virtual-host: /